<template>
  <a-layout id="components-layout-demo-fixed-sider">
    <a-layout-sider :style="{ overflow: 'auto', height: '100vh', position: 'fixed', left: 0 }" :trigger="null" collapsible v-model="collapsed" collapse="collapse">
      <div class="logo"></div>
      <a-menu theme="dark" mode="inline" :defaultSelectedKeys="['4']" :defaultOpenKeys="['sub1']">
        <a-sub-menu key="sub1">
          <span slot="title">
            <a-icon type="user"/>
            <span>subnav 1</span>
          </span>
          <a-menu-item key="1">option1</a-menu-item>
          <a-menu-item key="2">option2</a-menu-item>
          <a-menu-item key="3">option3</a-menu-item>
          <a-menu-item key="4">option4</a-menu-item>
        </a-sub-menu>
        <a-sub-menu key="sub2">
          <span slot="title">
            <a-icon type="laptop"/>
            <span>subnav 2</span>
          </span>
          <a-menu-item key="5">option5</a-menu-item>
          <a-menu-item key="6">option6</a-menu-item>
          <a-menu-item key="7">option7</a-menu-item>
          <a-menu-item key="8">option8</a-menu-item>
        </a-sub-menu>
        <a-sub-menu key="sub3">
          <span slot="title">
            <a-icon type="notification"/>
            <span>subnav 3</span>
          </span>
          <a-menu-item key="9">option9</a-menu-item>
          <a-menu-item key="10">option10</a-menu-item>
          <a-menu-item key="11">option11</a-menu-item>
          <a-menu-item key="12">option12</a-menu-item>
        </a-sub-menu>
      </a-menu>
    </a-layout-sider>
    <a-layout :style="{ marginLeft: !collapsed?'200px':'80px' }">
      <a-layout-header :style="{ background: '#f0f2f5'}" style="padding:0 16px;position:fixed;top:0;z-index:5;width:100%;">
        <!-- <div style="background-color:#fafafa;"> -->
        <a-icon class="trigger" :type="collapsed ? 'menu-unfold' : 'menu-fold'" @click="()=> collapsed = !collapsed"/>
        <!-- </div> -->
      </a-layout-header>
      <a-layout-content :style="{ margin: '24px 16px 0', overflow: 'initial' }">
        <div :style="{ padding: '24px', background: '#fff', textAlign: 'center' }">...
          <br>Really
          <br>...
          <br>...
          <br>...
          <br>long
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>...
          <br>content
        </div>
      </a-layout-content>
      <a-layout-footer :style="{ textAlign: 'center' }">Ant Design ©2018 Created by Ant UED</a-layout-footer>
    </a-layout>
  </a-layout>
</template>

<script>
export default {
  data () {
    return {
      collapsed: false
    }
  },
  method: {
    collapse (collapsed, type) {
      console.log(collapsed)
    }
  }
}
</script>

<style lang="scss" scoped>
#components-layout-demo-fixed-sider .logo {
  height: 32px;
  background: rgba(255, 255, 255, 0.2);
  margin: 16px;
}
#components-layout-demo-custom-trigger .trigger:hover {
  color: #1890ff;
}

#components-layout-demo-custom-trigger .logo {
  height: 32px;
  background: rgba(255, 255, 255, 0.2);
  margin: 16px;
}
</style>
